import json
from base64 import b64decode
from pathlib import Path

from findmy.accessory import FixedRollingKeyPairAccessory


def main(output: Path, devices_json: Path) -> int:
    with devices_json.open() as devices_json_file:
        devices = json.load(devices_json_file)
    device = devices[0]

    private_keys: list[bytes] = [
        b64decode(private_key) for private_key in device["additionalKeys"] + [device["privateKey"]]
    ]
    accessory: FixedRollingKeyPairAccessory = FixedRollingKeyPairAccessory(
        private_keys=private_keys, name=device["name"], identifier=str(device["id"])
    )

    accessory.to_json(output)

    return 0


if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--devices-json",
        type=Path,
        help="Input accessory JSON file as generated by macles-haystack",
        required=True,
    )
    parser.add_argument(
        "--output", type=Path, help="Output JSON file in format used by FindMy.py", required=True
    )
    args = parser.parse_args()

    sys.exit(main(args.output, args.devices_json))
